### ISSUE TITLE
Feedback addressed

### ISSUE THREAD

**Issue by Steve-JJ-He** [DSCI-310-2024/DSCI_310_Group_6#46]
Includes all the improvements made based on the peer feedback provided.

**Comment by gurmangill125** [comment]
Feedback:"Updating the README.md file in folders such as 'tests' could be beneficial to improve understanding of the files and their purposes. Currently, not all of the test code in this folder is documented."
Improvement: Improved README.md to be more clear on Docker analysis as well as running tests.
https://github.com/DSCI-310-2024/DSCI_310_Group_6_wine_quality_predictors/commit/e72ea0d965021880724cfcc33b66d686e3aa4972

**Comment by Steve-JJ-He** [comment]
Feedback: "Some folder names can be changed. For example, "model"; doesn't give the third party a clear idea of what it might contain."
Improvement: rename the folder to a more descriptive title
https://github.com/DSCI-310-2024/DSCI_310_Group_6_wine_quality_predictors/commit/89b358ca5fd0c44c9e87d9a3385fcc6a22e143f3

**Comment by Steve-JJ-He** [comment]
Feedback: "the repository has "README.md" and "Updated summary of README," which causes confusion; maybe this can be looked at."

improvement: delete the outdated version of readme file to avoid confusion
https://github.com/DSCI-310-2024/DSCI_310_Group_6_wine_quality_predictors/commit/5c606d46550c695190054107400b96a287fdafc5

**Comment by Steve-JJ-He** [comment]
Feedback:" I have noticed a small inconsistency in the naming conventions across the project. For instance, in the 'tests' directory, 'test_scatter_plot.R' uses an underscore, while the other tests use a combination of hyphens and underscores."
Improvement:
https://github.com/DSCI-310-2024/DSCI_310_Group_6_wine_quality_predictors/commit/9675475d93fcc0e5babfd395f5c9eda163d942e1

**Comment by Steve-JJ-He** [comment]
Feedback:"The repository contains several redundant files, such as renv-related files and a duplicate README. I believe the analysis should no longer require renv if Docker is properly implemented."
Improvement: removed the renv files
https://github.com/DSCI-310-2024/DSCI_310_Group_6_wine_quality_predictors/commit/7aac2c458ffb2e8570cd97f04f1b8dd8bc0a1ec8

**Comment by Steve-JJ-He** [comment]
Feedback:"Tests is missing the testthat subdirectory i.e., tests/testthat"
Improvement: creat testthat subdirectory and move all tests into the subdirectory
https://github.com/DSCI-310-2024/DSCI_310_Group_6_wine_quality_predictors/pull/47
